### ISSUE TITLE
Documentation to show how to set things like the popup height and width

### ISSUE THREAD

**Issue by megalithic** [vijaymarupudi/nvim-fzf-commands#1]
Hey there @vijaymarupudi!

Great library you have here. I'm really excited about all the things we can do here.

One thing I'm struggling to wrap my brain around, is, how we might go about setting TUI configuration for the resulting popup window. I see in nvim-fzf it does reference allowing to set height/width and some other "ui" settings for that centered popup window, but am unclear how/where to actually set it.

 Would love an additional bit of config/customization documentation in the README if you'd be up for it.

Thanks!

**Comment by vijaymarupudi** [comment]
Hello @megalithic!

There isn't a mechanism currently to customize the popup window, but there is a mechanism to provide your own window. I was awaiting progress in issue https://github.com/neovim/neovim/issues/6092 before moving forward on customization. 

The nvim-fzf library uses a hacky solution for the popup window (https://github.com/vijaymarupudi/nvim-fzf/blob/master/autoload/nvim_fzf.vim). I don't want to design the api over that mechanism, since a better mechanism is going to come soon.

I think the best way to go (for now, unfortunately, until https://github.com/neovim/neovim/issues/6092 is resolved) is to make a window you like, and making a custom fzf function with the parameters you desire.

**Comment by vijaymarupudi** [comment]
https://github.com/vijaymarupudi/nvim-fzf/issues/4

It looks like fzf has a border option, that I was not aware of. That solves the issue, give me some more time and you will have more customization options. Feel free to ping me in a month if I haven't implemented it yet.

**Comment by vijaymarupudi** [comment]
I've now documented this: https://github.com/vijaymarupudi/nvim-fzf-commands/commit/34c2c1813203519b82cb3ec058bb1c679feba74a

I hope that works!

**Comment by megalithic** [comment]
Thanks so much @vijaymarupudi !!
